### ISSUE TITLE
MicrosoftGraphService AuthenticationToken for silent service Initialization

### ISSUE THREAD

**Issue by mscherotter** [windows-toolkit/Graph-Controls#12]
## Describe the problem this feature would solve
With the MicrosoftGraphService, there is no way to persist the auth token to sign in silently after suspending/resuming.  The MicrosoftGraphService should have a way to save the auth token so subsequent sessions could login silently.

## Describe the solution
A way to login silently to the MicrosoftGraphService from a UWP in subsequent sessions.
## Describe alternatives you've considered
login every time an app starts (bad user experience)

**Comment by michael-hawker** [comment]
@skendrot the graph service is supposed to save the tokens in UWP and Xamarin scenarios. We try to check the state of the cache at initialization [here](https://github.com/windows-toolkit/Graph-Controls/blob/master/Microsoft.Toolkit.Graph/Providers/MsalProvider.cs#L81).

If that fails for some reason, we prompt again.  So it could be that there's some other error being thrown that we're not expecting.

**Comment by mscherotter** [comment]
This is how I login - and it always shows the oauth dialog.  Is there a permission scope I need for silent login?:
            MicrosoftGraphService.Instance.AuthenticationModel = AuthenticationModel.V1;

            if (!MicrosoftGraphService.Instance.Initialize(
                ClientId))
            {
                return false;
            }

           !await MicrosoftGraphService.Instance.TryLoginAsync()

**Comment by michael-hawker** [comment]
Ah, @mscherotter that's the old toolkit graph library stuff.  We've just replaced it all with new stuff built on top of the official updated Graph SDK and MSAL libraries in this repo under preview.  

Please try the new `Microsoft.Toolkit.Graph.Controls` library from MyGet.  The `LoginButton` can handle this all automatically.  There's info on the [homepage](https://aka.ms/wgt) about getting started.

If you have any questions about the new methods let me know.

**Comment by mscherotter** [comment]
I’ve added the new Button on my page and the provider in app.xaml but the button is staying disabled – I can’t click it – and no debug messages.
Please advise.
Michael

**Comment by Kyaa-dost** [comment]
@mscherotter Just to confirm are you compiling the code in debug mode?

**Comment by mscherotter** [comment]
I found the problem to be - if you have any other items in App.Resources, the login button fails to initialize correctly.

**Comment by michael-hawker** [comment]
@mscherotter I've been able to repro this.  I'm going to try and reach out to some of the XAML folks to understand the initialization procedures here.

In the mean time in your code-behind, you can initialize the provider like this:
```
            _ = Dispatcher.RunAsync(Windows.UI.Core.CoreDispatcherPriority.Normal, async () =>
            {
                ProviderManager.Instance.GlobalProvider = await QuickCreate.CreateMsalProviderAsync(
                    ClientId,
                    scopes: new string[] { "user.read", "user.readbasic.all", "people.read" });
            });
```

**Comment by michael-hawker** [comment]
Thanks for the dialog and report @mscherotter!  I've split off the issue about the resources into a separate issue and will close this one.
