### ISSUE TITLE
Closing the sign in window of AadLogin control causes unhandled exception

### ISSUE THREAD

**Issue by rikyuz** [windows-toolkit/Graph-Controls#22]
## Describe the bug
Closing the sign in popup window with title bar close button causes unhandled exception. I'm using Microsoft.Toolkit.Uwp.UI.Controls.Graph library version 5.1.0.

## Steps to Reproduce
1. Open a solution containing the [AadLogin](https://github.com/windows-toolkit/WindowsCommunityToolkit/tree/master/Microsoft.Toolkit.Uwp.UI.Controls.Graph/AadLogin) control. For example [Microsoft Graph Training Module](https://github.com/microsoftgraph/msgraph-training-uwp) solution.
2. Start debugging the solution and click the AadLogin button. A sign in page should appear on a popup window. 
3. Close the window by clicking the close button on the title bar.

![8hNr9xGnnG](https://user-images.githubusercontent.com/51473445/67928922-d065b900-fbc4-11e9-88ea-6b87631d81c9.png)

4. An unhandled exception of type "Microsoft.Identity.Client.MsalClientException" crashes the software with message: "User canceled authentication. On an Android device, this could be due to the lack of capabilities, such as custom tabs, for the system browser. See https://aka.ms/msal-net-system-browsers for more information."

![RhcvriBD4j](https://user-images.githubusercontent.com/51473445/67929053-13279100-fbc5-11e9-9f9f-2bcb8f20a5fb.png)

## Expected behavior
The window should close without exception being thrown.

## Environment

```
NuGet Package(s): 
Microsoft.Graph v1.19.0
Microsoft.NETCore.UniversalWindowsPlatform v6.2.9
Microsoft.Toolkit.Uwp.UI.Controls v5.1.1
Microsoft.Toolkit.Uwp.UI.Controls.DataGrid v5.1.0
Microsoft.Toolkit.Uwp.UI.Controls.Graph v5.1.0

Package Version(s): 

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [ ] Insider Build (build number: )
- [x] Version 1903 OS Build 18362.418

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [ ] Insider Build (xxxxx)
- [x] Windows 10, version 1809 (10.0; Build 17763)

Device form factor:
- [x] Desktop
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [x] 2017 (version: 15.9.17)
- [ ] 2019 (version: ) 
- [ ] 2019 Preview (version: )

```

## Additional context
Another issue I created about this earlier [Unhandled exception when login window is closed](https://github.com/microsoftgraph/msgraph-training-uwp/issues/27)

**Comment by rikyuz** [comment]
Okay, thanks. Notice that the bug probably originates from the [MicrosoftGraphService](https://github.com/windows-toolkit/WindowsCommunityToolkit/blob/master/Microsoft.Toolkit.Services/Services/MicrosoftGraph/MicrosoftGraphService.cs) class method TryLoginAsync.

The try-catch doesn't handle exceptions of type Microsoft.Identity.Client.MsalClientException?

**Comment by rikyuz** [comment]
I updated the Microsoft.Toolkit.Uwp.UI.Controls.Graph NuGet package to version 6.0.0 on my project and this issue still exists.

**Comment by shweaver-MSFT** [comment]
I've tested the LoginButton using the latest from dev/7.1.0 (which is where the preview controls live at the moment), and the exception was handled properly when I closed the dialogue.

Closing as fixed
