### ISSUE TITLE
MockProvider can't retrieve CalendarView events

### ISSUE THREAD

**Issue by michael-hawker** [windows-toolkit/Graph-Controls#27]
## Describe the bug
Calling this fails with MockProvider, works fine with InteractiveProvider:
```
                // Calendar Data, Today and Tomorrow (As Local)
                var today = DateTimeOffset.Now.Date.ToUniversalTime();
                var events = await provider.Graph.Me.CalendarView.Request(new[]
                {
                    new QueryOption("startDateTime", today.ToString("o", CultureInfo.InvariantCulture)),
                    new QueryOption("endDateTime", today.AddDays(2).ToString("o", CultureInfo.InvariantCulture)),
                }).OrderBy("start/dateTime").GetAsync();
```

## Expected behavior
Should retrieve events, see #24, seems like there's an issue in our workaround from #25 in order to get around the Graph SDK issue: https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/59

**Comment by HerrickSpencer** [comment]
@michael-hawker can you check the scope permissions for the clientid of mock provider?  I am thinking that it is set to the minimum user.read etc.  For this to work it needs to allow Scopes="User.Read,User.ReadBasic.All,People.Read,Calendars.Read"  
It also seems that the error coming back from the Graph SDK is incorrect/misleading, saying it needs datetime options set, even when they are. Really the error must be scoping or something of the kind.

**Comment by michael-hawker** [comment]
Thanks @HerrickSpencer had missed your comment. The proxy I don't think needs most scopes.

I managed to resolve this issue finally (and hopefully for good) in this commit here: https://github.com/windows-toolkit/Graph-Controls/pull/18/commits/dc8a6417d6f68d0b7f8a9ab5d3095077946d229b
