### ISSUE TITLE
Microsoft.Toolkit.Graph should be .NET Standard?

### ISSUE THREAD

**Issue by michael-hawker** [windows-toolkit/Graph-Controls#60]
It's multi-targeted to UWP currently, but think this can be .NET Standard only?

We need to test if we can just remove this and have MSAL still work?

**Comment by shweaver-MSFT** [comment]
This was changed in PR #76.

Now the main `CommunityToolkit.Net.Authentication` package no longer relies on the Graph SDK. All Graph SDK interaction is relegated to the `CommunityToolkit.Net.Graph` package
