### ISSUE TITLE
MsalProvider should be built on top of Msal.NET directly instead of Microsoft.Graph.Auth

### ISSUE THREAD

**Issue by nmetulev** [windows-toolkit/Graph-Controls#78]
## Describe the problem this feature would solve
MsalProvider is currently built on top of Microsoft.Graph.Auth which in itself is built on top of Msal.NET. The toolkit providers should not take a dependency on any Graph packages and avoid the additional overhead by building directly on top of Msal.NET

**Comment by shweaver-MSFT** [comment]
This was changed in PR #76.

The `MsalProvider` now lives in it's own dedicated `CommunityToolkit.Net.Authentication.Msal` package, built on the official `Microsoft.Identity.Client.Extensions.Msal` package.
