### ISSUE TITLE
[Feature] Create StateTrigger for SignedIn State

### ISSUE THREAD

**Issue by michael-hawker** [windows-toolkit/Graph-Controls#9]
## Describe the problem this feature would solve
Would be great to have [StateTrigger](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.statetrigger) and/or some other XAML helpers for the current state of authentication (loading, signed-in, signed-out) so that controls or other UI could be shown/hidden easily.

**Comment by shweaver-MSFT** [comment]
I attempted to create a ProviderStateTrigger, but I ran into some issues getting it to work. Basically the constructor is never called, and neither are any property setters when the trigger is created in XAML. This makes it impossible to listen for changes in the GlobalProvider and renders the trigger useless.

My attempt lives here:
https://github.com/windows-toolkit/Graph-Controls/blob/shweaver/provider-trigger/CommunityToolkit.Graph.Uwp/Triggers/ProviderStateTrigger.cs
