### ISSUE TITLE
[Feature] Create XAML helpers for handling provider state

### ISSUE THREAD

**Issue by nmetulev** [windows-toolkit/Graph-Controls#97]
There are few ways we could help developers manage the provider states in XAML

1. Add a new trigger that will allow developers to set VisualState based on a the current provider state
    ```xml
    <Page>
        <Grid>
            <VisualStateManager.VisualStateGroups>
                <VisualStateGroup>
                    <VisualState>
                        <VisualState.StateTriggers>
                            <communityToolkit:AuthStateTrigger State="SignedIn" />
                        </VisualState.StateTriggers>
    
                        <VisualState.Setters>
                            <Setter Target="myGrid.Visibility" Value="Visible" />
                        </VisualState.Setters>
                    </VisualState>
                </VisualStateGroup>
            </VisualStateManager.VisualStateGroups>
            <Grid x:Name="myGrid" Visibility="Collapsed">
                ...
            </Grid>
        </Grid>
    </Page>
    ```
2. Add a new extension to help with the most common scenario, setting visibility
    ```xml
    <Grid communityToolkit:VisibleWhenSignedIn="True">
        ....
    </Grid
    ```

**Comment by shweaver-MSFT** [comment]
I attempted to create a ProviderStateTrigger, but I ran into some issues getting it to work. Basically the constructor is never called, and neither are any property setters when the trigger is created in XAML. This makes it impossible to listen for changes in the GlobalProvider and renders the trigger useless.

My attempt lives here:
https://github.com/windows-toolkit/Graph-Controls/blob/shweaver/provider-trigger/CommunityToolkit.Graph.Uwp/Triggers/ProviderStateTrigger.cs

**Comment by michael-hawker** [comment]
@shweaver-MSFT [`NetworkConnectionStateTrigger`](https://github.com/windows-toolkit/WindowsCommunityToolkit/blob/main/Microsoft.Toolkit.Uwp.UI/Triggers/NetworkConnectionStateTrigger.cs) should be a good trigger to pattern off of. I tested in the sample app that it's working great and detecting a disabled/disconnected internet connection. 🙂

Maybe double-check that the VSM itself is working and is setup proper in the example? I think it can only work at the root element of a page, so it won't work in a nested Grid for instance.

**Comment by shweaver-MSFT** [comment]
@michael-hawker I got it working :) I was just doing it wrong. Check it out! I baked it right into the SampleTest app as an easy way to test it. #107
